[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1.39", features = ["full"] }
runtime-core = { path = "../runtime-core" }
deno_core = "0.338"
